### ISSUE TITLE
Error: invalid BigNumber value (argument="value", value=undefined, code=INVALID_ARGUMENT, version=bignumber/5.6.2)

### ISSUE THREAD

**Issue by html5css3-pro** [YourJustice-Live/Glamdring#102]
[https://prnt.sc/o-tQ1M7Nt_1u](url)

**Comment by kiv1n** [comment]
Thanks for finding the bug. We will fix this in the next release 👌

**Comment by kiv1n** [comment]
The bug has been fixed in version 0.3.4.

🔗https://github.com/YourJustice-Live/Glamdring/releases/tag/v0.3.4

**Comment by kiv1n** [comment]
The bug has been fixed in version 0.3.4.

🔗https://github.com/YourJustice-Live/Glamdring/releases/tag/v0.3.4
